import { useEffect, useRef, useState, type ReactNode } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useConnect, useConnection, useConnectors, useDisconnect, useSwitchChain, useWalletClient } from 'wagmi';
import { arcTestnet } from 'viem/chains';
import { formatUnits, isAddressEqual, type Address, type WriteContractParameters } from 'viem';
import NumberFlow from '@number-flow/react';
import { toast } from 'sonner';
import { Badge, Copy, Help, Modal, Panel } from '../components/ui';
import { configured, contextKey, explorer, manifest, maximumDraw, readSnapshot, simulate } from '../data/client';
import { blockNumber, decimal, delta, duration, freshness, grossBps, json, money, parseAmount, percent, short, utc } from '../data/format';
import { describeVerdict, REASONS } from '../data/reasons';
import { EXPOSURE_REASONS, HEDGE_REASONS, STATES, type Action, type Hedge, type LedgerRow, type Snapshot, type Verdict } from '../data/types';
import { downloadLedger, loadJournal, recordedAt, recordedRows, saveJournal, snapshotSummary, waiverProof } from '../data/ledger';
import { executeAction, HeldAction, recoverRow } from '../data/transactions';

function preference(key:string,fallback:string){try{return localStorage.getItem(key)??fallback;}catch{return fallback;}}
const docsUrl=import.meta.env.VITE_DOCS_URL||'https://github.com/estmcmxci/signa-arc#readme';
const testEntry=import.meta.env.DEV&&location.pathname.startsWith('/test-ui/');
// ?chain= runs the live paths against the in-page chain and wallet of src/test/harness.ts; ?state= shows snapshot fixtures.
const chainFixture=testEntry&&new URLSearchParams(location.search).has('chain');
const isFixture=testEntry&&!chainFixture;
export function Desk(){
  const queryClient=useQueryClient();
  const connection=useConnection();const connectors=useConnectors();const connect=useConnect();const disconnect=useDisconnect();const switchChain=useSwitchChain();const wallet=useWalletClient();
  const [amount,setAmount]=useState('1');const [debounced,setDebounced]=useState('1');
  const [now,setNow]=useState(Date.now());const [density,setDensity]=useState(()=>preference('signa:density','default'));const [theme,setTheme]=useState(()=>preference('signa:theme','dark'));
  const [fixture,setFixture]=useState(new URLSearchParams(location.search).get('state')??'compliant');
  const [rows,setRows]=useState<LedgerRow[]>(()=>{try{return loadJournal(localStorage);}catch{return [];}});
  const rowsRef=useRef(rows);const [storageIssue,setStorageIssue]=useState('');const [notice,setNotice]=useState('');
  const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [detail,setDetail]=useState<LedgerRow|null>(null);
  const [credential,setCredential]=useState<Hedge|null>(null);const [commandOpen,setCommandOpen]=useState(false);
  const [confirmation,setConfirmation]=useState<Exclude<Action,'approve'>|null>(null);const [activeAction,setActiveAction]=useState<Action|null>(null);
  const actionLock=useRef(false);const amountRef=useRef<HTMLInputElement>(null);const [maxResult,setMaxResult]=useState<{amount:bigint;block:string}|null>(null);const [findingMax,setFindingMax]=useState(false);
  const [history,setHistory]=useState<{block:bigint;bps:number}[]>([]);
  useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
  useEffect(()=>{const t=setTimeout(()=>setDebounced(amount),250);setMaxResult(null);return()=>clearTimeout(t);},[amount]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('signa:theme',theme);}catch{}},[theme]);
  useEffect(()=>{try{localStorage.setItem('signa:density',density);}catch{}},[density]);
  const snapshotQuery=useQuery({queryKey:['facility',contextKey,isFixture?fixture:'live'],queryFn:async()=>isFixture?(await import('../test/fixtures')).fixtureSnapshot(fixture):readSnapshot(),refetchInterval:4000,staleTime:2000});
  const snapshot=snapshotQuery.data;const m=manifest;const c=snapshot?.coverage;const p=snapshot?.policy;
  const estimatedChainNow=snapshot?snapshot.block.timestamp+BigInt(Math.max(0,Math.floor((now-snapshot.receivedAt)/1000))):0n;
  const readStale=Boolean(snapshot&&(snapshotQuery.isError||now-snapshot.receivedAt>12000));
  // The registry returns an all-zero record when no exposure was ever accepted; the engine reads digest 0 as MISSING.
  const exposure=snapshot?.exposure&&BigInt(snapshot.exposure.digest)!==0n?snapshot.exposure:null;const noExposure=Boolean(snapshot?.exposure)&&!exposure;
  const exposureFresh=exposure&&p?freshness(exposure.credential.observedAt,exposure.credential.validUntil,p.credentialMaxAge,estimatedChainNow):null;
  const expiryCrossed=Boolean(exposureFresh?.state==='STALE'&&c?.exposureReason===0);
  const sender=(connection.address??m?.roles.operator) as Address|undefined;
  let parsed:bigint|null=null;let inputIssue='';try{parsed=parseAmount(amount);}catch(e){inputIssue=(e as Error).message;}
  let queryAmount:bigint|null=null;try{queryAmount=parseAmount(debounced);}catch{}
  const preflightKey=['preflight',contextKey,sender,connection.chainId,debounced,snapshot?.block.hash,isFixture?fixture:'live'];const blockPosition=5;
  // Arc produces about two blocks a second, so every poll re-keys this query. Keep the verdict on screen while the
  // same request is re-evaluated at the new block; any other change discards it, so no stale permit can be shown.
  const sameRequest=(key:readonly unknown[])=>key.length===preflightKey.length&&preflightKey.every((part,index)=>index===blockPosition||part===key[index]);
  const preflight=useQuery({queryKey:preflightKey,queryFn:async()=>isFixture?(await import('../test/fixtures')).fixtureVerdict(fixture,queryAmount!,sender!,snapshot!.block):simulate('draw',queryAmount!,sender!,snapshot!.block),enabled:Boolean(sender&&queryAmount&&snapshot&&!readStale&&!expiryCrossed),retry:1,staleTime:3000,placeholderData:(previous,query)=>query&&sameRequest(query.queryKey)?previous:undefined});
  const verdict=parsed!==null&&amount===debounced&&!readStale&&!expiryCrossed?preflight.data:undefined;
  const explanation=verdict?describeVerdict(verdict,snapshot):null;
  const pending=rows.filter(r=>r.kind==='transaction'&&(r.status==='pending'||r.status==='unknown'||r.status==='awaiting')&&r.facilityId===m?.facility.id);
  const walletReady=connection.isConnected&&connection.chainId===arcTestnet.id;
  const operator=walletReady&&Boolean(connection.address&&m&&isAddressEqual(connection.address,m.roles.operator));
  const state=snapshot?.state===null||snapshot?.state===undefined?'UNAVAILABLE':STATES[snapshot.state]??'UNKNOWN';
  const record=(row:LedgerRow)=>{
    const next=[...rowsRef.current.filter(r=>r.id!==row.id),row].slice(-500);rowsRef.current=next;setRows(next);
    try{saveJournal(localStorage,next);}catch{setStorageIssue('Browser storage is unavailable. Keep transaction hashes before closing this page.');}
  };
  useEffect(()=>{if(c&&snapshot){setHistory(prior=>prior.some(point=>point.block===snapshot.block.number)?prior:[...prior,{block:snapshot.block.number,bps:c.coverageBps}].slice(-60));}},[snapshot?.block.hash,c?.coverageBps]);
  useEffect(()=>{setNotice('');setConfirmation(null);setMaxResult(null);},[connection.address,connection.chainId]);
  useEffect(()=>{
    function keyboard(e:KeyboardEvent){const target=e.target as HTMLElement; if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setCommandOpen(v=>!v);return;}
      if(target.closest('input,textarea,select,[contenteditable="true"],[role="dialog"]')||e.metaKey||e.ctrlKey||e.altKey)return;
      if(e.key==='d'){e.preventDefault();amountRef.current?.focus();}
      if(e.key==='s'){e.preventDefault();document.getElementById('sync-action')?.focus();}
      if(e.key==='j'||e.key==='k'){const elements=Array.from(document.querySelectorAll<HTMLElement>('[data-ledger-detail]'));const i=elements.indexOf(document.activeElement as HTMLElement);elements[Math.max(0,Math.min(elements.length-1,i+(e.key==='j'?1:-1)))]?.focus();}
    }window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard);
  },[]);
  function heldRecord(v:Verdict){if(!m)return;record({id:crypto.randomUUID(),source:'local',kind:'simulation',action:v.action,amount:v.amount.toString(),actor:v.sender,status:'held',timestamp:new Date().toISOString(),block:v.block.number.toString(),code:v.code,chainId:5042002,facilityId:m.facility.id,...(c?{coverageBps:c.coverageBps}:{})});}
  function prepare(action:Exclude<Action,'approve'>){
    setNotice('');
    if(isFixture){setNotice('Labelled UI fixture: live signing and transaction submission are disabled.');return;}
    if(action==='draw'&&verdict&&verdict.kind!=='permitted'){heldRecord(verdict);setNotice('This held simulation is recorded below. No transaction was sent.');return;}
    if(!walletReady){setNotice('Connect a wallet on Arc Testnet to perform an action. The preview above uses the facility operator.');return;}
    if((action==='draw'||action==='repay')&&!operator){setNotice('Draw and repayment require the facility operator account.');return;}
    if(activeAction||pending.length){setNotice('Reconcile the outstanding wallet operation before submitting another. Reads and evidence remain available.');return;}
    if((action==='draw'||action==='repay')&&parsed===null){setNotice(inputIssue);return;}
    if(readStale||!snapshot||snapshotQuery.isError){setNotice('Refresh the current facility snapshot before preparing a transaction.');return;}
    if(action==='draw'&&(!verdict||verdict.kind!=='permitted')){setNotice('Wait for the current amount’s evaluation.');return;}
    setConfirmation(action);
  }
  async function submit(){
    const action=confirmation;if(!action||!connection.address||!wallet.data||isFixture||actionLock.current)return;
    actionLock.current=true;setConfirmation(null);setActiveAction(action);const id=toast.loading('Preparing the transaction…');
    const walletClient=wallet.data;let latest:LedgerRow|undefined;
    try{
      await executeAction(action,parsed??0n,{address:connection.address,getAddress:async()=>{const addresses=await walletClient.getAddresses();if(!addresses[0])throw new Error('Wallet disconnected');return addresses[0];},getChainId:()=>walletClient.getChainId(),send:request=>walletClient.writeContract(request as WriteContractParameters)},row=>{
        latest=row;record(row);const messages={awaiting:'Awaiting wallet approval',pending:'Submitted · waiting for confirmation',confirmed:'Transaction confirmed',reverted:'Transaction reverted on-chain',unknown:'Confirmation unresolved',declined:'Wallet request declined',cancelled:'Transaction cancelled',held:'Held by the covenant'};
        toast(messages[row.status],{id,description:row.hash?short(row.hash):row.action,duration:row.status==='pending'||row.status==='awaiting'?Infinity:6000});
      });
    }catch(e){if(e instanceof HeldAction){heldRecord(e.verdict);setNotice(`${describeVerdict(e.verdict,snapshot).title}. No transaction was sent for that step.`);toast.dismiss(id);}else{
      // A library error arrives as a multi-line message with its own version line. Show the sentence this browser
      // recorded for the ledger row and keep the raw text in that row's detail; our own errors already read plainly.
      const raw=(e as Error).message;const brief=(e as {shortMessage?:string}).shortMessage;
      setNotice((brief===undefined?raw:latest?.message??brief)||'Review wallet activity and the ledger before retrying.');
      if(latest&&brief!==undefined&&raw)record({...latest,detail:raw});
      toast('Review the operation',{id,description:'Its latest known outcome remains in the ledger.'});}}
    finally{actionLock.current=false;setActiveAction(null);void queryClient.invalidateQueries({queryKey:['facility']});void queryClient.invalidateQueries({queryKey:['preflight']});}
  }
  async function reconcile(row:LedgerRow){setNotice('Checking for a receipt…');const updated=await recoverRow(row);record(updated);setNotice(updated.status==='unknown'?'A receipt is not available yet. No transaction was resent.':'The ledger now reflects the receipt.');void snapshotQuery.refetch();}
  const allRows=[...rows,...recordedRows].filter(r=>r.facilityId===m?.facility.id).filter(r=>filter==='all'||filter==='held'?(filter==='all'||r.status==='held'||r.status==='reverted'):filter==='local'?r.source==='local':r.source==='recorded').filter(r=>`${r.action} ${r.code??''} ${r.hash??''} ${r.actor??''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.timestamp.localeCompare(a.timestamp));
  const agenda=readStale?'The latest read is unavailable. Refresh before acting.':expiryCrossed?'Exposure evidence has aged past its validity. Waiting for a new chain evaluation.':c&&!c.compliant?'Current evidence does not meet the coverage policy. Review the excluded assertions below.':snapshot?.available===0n?'Coverage is sufficient; all remaining vault funds are retained as reserve.':c?'The coverage policy is met. Each draw is evaluated again before signing.':'Reading the facility’s current condition…';
  return <div className="desk" data-density={density}>
    <a href="#main" className="skip-link">Skip to operator desk</a>
    <header className="topbar"><a href="/" className="wordmark"><img src="/favicon.png" alt="" aria-hidden="true" width={20} height={20} style={{alignSelf:'center',borderRadius:'50%'}} />Signa <span>Covenant</span></a><nav aria-label="Primary"><a href={docsUrl}>Docs ↗</a><a href="/security/">Trust boundary</a><button className="quiet" onClick={()=>setCommandOpen(true)} aria-keyshortcuts="Control+k Meta+k">Commands <kbd>⌘ K</kbd></button><button className="icon-button" aria-label={`Use ${theme==='dark'?'light':'dark'} theme`} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☼':'◐'}</button></nav></header>
    <main id="main" className="desk-main">
      <div className={`truth-strip ${testEntry?'fixture-strip':''}`}>{isFixture?'UI FIXTURE · fabricated test state · signing disabled':chainFixture?'UI FIXTURE · simulated chain and wallet in this page · no network, no keys, no real transactions':'Arc Testnet · fictional facility · labelled mock issuer data · testnet USDC'}</div>
      {isFixture&&<label className="fixture-select">Test state <select value={fixture} onChange={e=>setFixture(e.target.value)}>{['compliant','reserve','cure','breach','waived','expired-waiver','stale','missing','revoked','maturity','partial','rpc-error','slow'].map(s=><option key={s}>{s}</option>)}</select></label>}
      <div className="facility-heading"><div><p className="eyebrow">Operator desk / 01</p><h1>EUR / USD facility</h1><p className="facility-id">{m?<Copy value={m.facility.id} label="facility ID"/>:'Deployment unavailable'}</p></div><div className="wallet-area">{connection.isConnected?<><Copy value={connection.address!} label="connected address"/><button className="quiet" onClick={()=>disconnect.mutate({})}>Disconnect</button>{connection.chainId!==5042002&&<button onClick={()=>switchChain.mutate({chainId:5042002})}>Switch to Arc Testnet</button>}{walletReady&&!operator&&<span className="caption">Connected account is not the facility operator.</span>}</>:<><button onClick={()=>{if(connectors[0])connect.mutate({connector:connectors[0]});else setNotice('No injected browser wallet was found. Read-only inspection and simulation remain available.');}}>Connect wallet</button>{connectors.length>1&&<select aria-label="Choose wallet" defaultValue="" onChange={e=>{const connector=connectors.find(c=>c.uid===e.target.value);if(connector)connect.mutate({connector});}}><option value="" disabled>Choose another wallet</option>{connectors.map(c=><option key={c.uid} value={c.uid}>{c.name}</option>)}</select>}</>}{connect.error&&<p role="alert">{connect.error.name==='UserRejectedRequestError'?'Wallet connection declined.':'Wallet connection did not complete. Retry in your wallet.'}</p>}</div></div>
      <section className="attention" aria-label="Facility condition"><Badge state={state}/><p>{agenda}</p><button className="quiet" onClick={()=>void snapshotQuery.refetch()} aria-label="Refresh facility">↻ Refresh</button></section>
      <div className="read-context"><span>{snapshot?`Snapshot: block ${blockNumber(snapshot.block.number)} · ${utc(snapshot.block.timestamp)}`:'Awaiting a current block'}</span><span>{snapshot?`${duration((now-snapshot.receivedAt)/1000)} since read`:'Reading…'}{snapshotQuery.isFetching?' · refreshing':''}</span></div>
      {snapshot?.issues.length? <div className="notice error" role="status">Some fields are unavailable: {snapshot.issues.join(', ')}. Other figures share the displayed block.</div>:null}
      {snapshotQuery.isError&&<div className="notice error" role="alert">Current reads are unavailable. {snapshot?'The last confirmed snapshot is marked stale.':'No prior values are available.'}<button onClick={()=>void snapshotQuery.refetch()}>Retry</button></div>}
      <section className={`metrics ${readStale||expiryCrossed?'stale-values':''}`} aria-label="Facility metrics">
        <Metric label="Counted coverage" help="The engine caps counted cover at the authenticated exposure. Only counted cover governs the ratio." value={c?percent(c.coverageBps):'—'} note={c?`${delta(c.coverageBps,c.requiredCoverageBps)} to ${percent(c.requiredCoverageBps)} minimum`:'Awaiting engine'}>{c&&!readStale&&!expiryCrossed?<NumberFlow value={c.coverageBps/100} format={{minimumFractionDigits:2,maximumFractionDigits:2}} suffix="%" respectMotionPreference/>:null}</Metric>
        <Metric label="Gross coverage" help="Gross eligible cover remains visible before the exposure cap." value={c?percent(grossBps(c.grossEligible,c.outstandingValue)):'—'} note={c?`${money(c.grossEligible,6)} USDC eligible`:'Awaiting engine'}/>
        <Metric label="Available to draw" help="Confirmed vault liquidity above the retained reserve. Coverage is checked separately." value={money(snapshot?.available)} unit="USDC" note={pending.length?`${pending.length} unresolved operation(s); not deducted here`:`${money(p?.reserveAmount)} USDC retained reserve`}/>
        <Metric label="Authenticated exposure" help="USD obligation asserted by the exposure issuer for the EUR-denominated book. Not a token balance." value={noExposure?'—':money(c?.outstandingValue)} unit="USDC" note={exposureFresh?`${exposureFresh.state.toLowerCase()} · ${duration(exposureFresh.age)} old`:noExposure?'No exposure recorded':'Evidence unavailable'}/>
      </section>
      <div className="operator-grid">
        <Panel title="Coverage gate" kicker="Evaluate a draw" id="actions" aside={<span className="caption">{connection.address?'Connected-account preview':'Operator preview · read only'}</span>}>
          <div className="amount-field"><label htmlFor="draw-amount">Draw / repay amount</label><div><input ref={amountRef} id="draw-amount" inputMode="decimal" autoComplete="off" value={amount} onChange={e=>setAmount(e.target.value)} aria-describedby="amount-help" aria-invalid={!!inputIssue}/><span>USDC</span></div><p id="amount-help" className="caption">{inputIssue||`Exact request: ${money(parsed,6)} USDC`}</p></div>
          <div className={`verdict ${verdict?.kind==='system'?'error':verdict?.kind==='permitted'?'ok':'hold'}`} aria-live="polite" aria-busy={preflight.isFetching}>
            {explanation&&verdict?<><Badge state={verdict.kind==='permitted'?'PERMITTED':verdict.kind==='system'?'READ FAILED':'HELD'}/><h3>{explanation.title}</h3><dl className="verdict-facts"><dt>Rule</dt><dd>{explanation.rule}</dd><dt>Observed</dt><dd>{explanation.observed}</dd><dt>Required</dt><dd>{explanation.required}</dd>{snapshot?.exposure&&<><dt>Evidence</dt><dd>{exposure?`Exposure observed ${utc(exposure.credential.observedAt)}`:'No exposure recorded'}{c?`; ${c.eligibleHedgeCount} of ${c.totalHedgeCount} hedges eligible`:''}</dd></>}</dl><p>{explanation.remedy}</p><p className="caption">Who can act: {explanation.actor} · block {blockNumber(verdict.block.number)}</p><Copy value={explanation.code} label="reason code" full/></>:<><Badge state="UNASSESSED"/><h3>{inputIssue?'Review the amount':readStale||expiryCrossed?'Awaiting current evidence':preflight.isError?'Evaluation unavailable':'Evaluating the draw'}</h3><p>{inputIssue||'The preview uses the vault’s own simulation. No transaction is sent.'}</p></>}
          </div>
          <div className="action-row"><button className="primary" aria-disabled={!operator||verdict?.kind!=='permitted'||!!activeAction||pending.length>0||isFixture} onClick={()=>prepare('draw')}>Draw USDC</button><button aria-disabled={!operator||!!activeAction||pending.length>0||isFixture} onClick={()=>prepare('repay')}>Repay</button><button className="quiet" id="sync-action" aria-disabled={!walletReady||!!activeAction||pending.length>0||isFixture} onClick={()=>prepare('syncCovenant')}>Sync covenant</button><button className="quiet" aria-disabled={!walletReady||!!activeAction||pending.length>0||isFixture} onClick={()=>prepare('restoreCompliance')}>Restore</button></div>
          <p className="caption">{isFixture?'Fixture mode never requests a signature.':!connection.address?'Connect the operator wallet to draw or repay. Sync and restore are permissionless.':'Every action is freshly simulated before signing. Repayment does not change the signed exposure.'}</p>
          <details className="explore"><summary>Explore a smaller draw</summary><p className="caption">Find the largest permitted amount at this snapshot. A later transaction is evaluated again.</p><button aria-disabled={!snapshot||readStale||findingMax||isFixture} onClick={async()=>{if(!snapshot||!sender||readStale||isFixture||findingMax)return;setFindingMax(true);try{const result=await maximumDraw(snapshot,sender);setMaxResult({amount:result.amount,block:snapshot.block.number.toString()});}catch(e){setNotice((e as Error).message);}finally{setFindingMax(false);}}}>{findingMax?'Evaluating…':'Find permitted amount'}</button>{maxResult&&<div><p>{money(maxResult.amount,6)} USDC permitted at block {blockNumber(maxResult.block)}.</p>{maxResult.amount>0n&&<><label htmlFor="draw-range">Portion of simulated maximum</label><input id="draw-range" type="range" min="1" max="100" defaultValue="100" onChange={e=>setAmount(decimal(maxResult.amount*BigInt(e.target.value)/100n))}/><button onClick={()=>setAmount(decimal(maxResult.amount))}>Use maximum</button></>}</div>}</details>
        </Panel>
        <div className="right-stack"><Panel title="Frozen facility policy" kicker="USD settlement / EUR exposure"><dl className="facts"><Fact label="Coverage minimum" value={p?percent(p.minCoverageBps):'—'} help="Counted cover required as a share of signed exposure."/><Fact label="Default haircut" value={p?percent(p.defaultHaircutBps):'—'} help="The engine discounts each eligible hedge before aggregation."/><Fact label="Maximum evidence age" value={p?duration(p.credentialMaxAge):'—'} help="A new synchronization does not renew an old issuer observation."/><Fact label="Maturity tolerance" value={p?duration(p.maturityTolerance):'—'} help="Hedge maturity plus tolerance must reach exposure maturity."/><Fact label="Principal drawn" value={`${money(snapshot?.principal,6)} USDC`} help="Repayment reduces this principal, not the signed exposure obligation."/><Fact label="Retained reserve" value={`${money(p?.reserveAmount,6)} USDC`} help="Every draw leaves at least this amount in the vault."/><Fact label="Cure window" value={p?duration(p.curePeriod):'—'} help="Time to remedy; draws are held during cure."/><Fact label="Cure deadline" value={utc(snapshot?.cureDeadline)} help="Sync records expiry; passing time does not repair evidence."/></dl></Panel>
          <Panel title="How cover is counted" kicker="Engine output"><CoverageBar snapshot={snapshot}/><div className="coverage-caption"><span>Counted <strong>{money(c?.countedEligible,6)}</strong></span><span>Gross <strong>{money(c?.grossEligible,6)}</strong></span></div><p className="caption">USDC · surplus above the exposure is visible, but not counted.</p><Sparkline points={history} threshold={p?.minCoverageBps??10000}/></Panel></div>
      </div>
      {notice&&<div className="notice" role="status">{notice}</div>}{storageIssue&&<div className="notice error" role="alert">{storageIssue}</div>}
      <Panel title="Independent assertions" kicker="Evidence under the covenant" id="credentials" aside={<span className="mock-tag">Mock provider data</span>}>
        <div className="exposure-strip"><div><h3>Exposure assertion <span className="mock-tag">Mock issuer</span></h3><p>{exposure?<Copy value={exposure.issuer} label="exposure issuer"/>:noExposure?'No exposure recorded':'Issuer unavailable'}</p></div><div><span className="caption">Observed / effective expiry</span><p>{exposure?utc(exposure.credential.observedAt):'—'}</p><p className="caption">{exposureFresh?utc(exposureFresh.expires):'—'}</p></div><div>{exposureFresh?<Badge state={exposureFresh.state}/>:noExposure?<Badge state="NONE">NO EXPOSURE</Badge>:<Badge state="UNAVAILABLE"/>}<p className="caption">{c?(REASONS[EXPOSURE_REASONS[c.exposureReason]??'']?.title??'Reason unavailable'):'Reason unavailable'}</p>{exposure&&<p className="caption">Sequence {exposure.credential.sequence.toString()}</p>}</div></div>
        <div className="table-scroll"><table><caption className="sr-only">Active hedge assertions and engine eligibility</caption><thead><tr><th>Hedge / issuer</th><th className="num">Remaining USDC</th><th>Freshness</th><th>Maturity UTC</th><th>Engine decision</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{snapshot?.hedges?.map(h=>{const fresh=p?freshness(h.credential.observedAt,h.credential.validUntil,p.credentialMaxAge,estimatedChainNow):null;const code=h.eligibilityReason===null?'UNAVAILABLE':HEDGE_REASONS[h.eligibilityReason]??'UNKNOWN';return <tr key={h.credential.tradeIdCommitment}><td><span className="mono">{short(h.credential.tradeIdCommitment)}</span><span className="cell-secondary mono">{short(h.issuer)} · mock</span></td><td className="num" title={`${money(h.credential.remainingNotional,6)} USDC`}>{money(h.credential.remainingNotional)}</td><td>{fresh?<><Badge state={fresh.state}/><span className="cell-secondary">{fresh.remaining<0n?'Expired '+duration(-fresh.remaining)+' ago':duration(fresh.remaining)+' remaining'}</span></>:'—'}</td><td>{utc(h.credential.maturity).slice(0,10)}</td><td><span>{REASONS[code]?.title??'Unavailable'}</span><span className="cell-secondary mono">{code}</span></td><td><button onClick={()=>setCredential(h)} aria-label={`Inspect hedge ${short(h.credential.tradeIdCommitment)}`}>Inspect</button></td></tr>;})??<tr><td colSpan={6}>Hedge reads are unavailable.</td></tr>}{snapshot?.hedges?.length===0&&<tr><td colSpan={6}>No active hedge IDs in this snapshot.</td></tr>}</tbody></table></div>
        <p className="caption">A signature authenticates who asserted these fields. It does not prove a hedge legally exists. {m?.exposureDenomination&&<><a href={`${explorer}/address/${m.exposureDenomination.referenceAsset.address}`}>EURC ↗</a> is referenced as the book’s denominating asset; the vault never moves it.</>}</p>
      </Panel>
      <Panel title="Governed exceptions" kicker="A waiver does not restore coverage" id="waiver" aside={<Badge state={snapshot?.activeWaiver?'WAIVED':'UNASSESSED'}>{snapshot?.activeWaiver?'WAIVER ACTIVE':'NO ACTIVE WAIVER'}</Badge>}>
        <div className="waiver-grid"><div><p>{snapshot?.activeWaiver?`Permitted under a bounded exception. Underlying evidence: ${c?.compliant?'compliant':'below policy or ineligible'}.`:'The facility administrator is a 2-of-2 quorum. Neither approver can create a waiver alone.'}</p><p className="caption">Current ratio {c?percent(c.coverageBps):'—'} / {c?percent(c.requiredCoverageBps):'—'} required. Reserve retention still applies during a waiver.</p>{snapshot?.waiverEndsAt!==null&&snapshot?.waiverEndsAt!==undefined&&snapshot.waiverEndsAt>0n&&<p>Recorded expiry: {utc(snapshot.waiverEndsAt)}{snapshot.waiverEndsAt<estimatedChainNow?' · expired':''}</p>}{snapshot?.activeWaiver&&snapshot.waiverReason&&<Copy value={snapshot.waiverReason} label="waiver reason commitment" full/>}</div><div><p className="caption">Recorded quorum approval · {waiverProof.at.slice(0,10)}</p><a href={`${explorer}/tx/${waiverProof.hash}`}>Inspect the approved waiver ↗</a><p className="caption">Approvals happen in the existing approver console. This desk has no admin-key bypass.</p></div></div>
      </Panel>
      <Panel title="Decision & transaction ledger" kicker="Permitted and held, at equal weight" id="ledger" aside={<div className="export-controls"><button onClick={()=>downloadLedger(allRows,'csv')}>Export CSV</button><button onClick={()=>downloadLedger(allRows,'json')}>JSON</button></div>}>
        <div className="ledger-tools"><label>Show <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All decisions</option><option value="held">Held / reverted</option><option value="local">This browser</option><option value="recorded">Recorded evidence</option></select></label><label><span className="sr-only">Search ledger</span><input placeholder="Search action, hash or reason" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Density <select value={density} onChange={e=>setDensity(e.target.value)}><option value="compact">Compact</option><option value="default">Default</option><option value="comfortable">Comfortable</option></select></label></div>
        <p className="caption">Historical evidence recorded {recordedAt.slice(0,10)} plus decisions kept in this browser (up to 500). This is not a complete index of every transaction or simulation.</p>
        <div className="table-scroll"><table><caption className="sr-only">Source-labelled decisions and receipts</caption><thead><tr><th>Action / source</th><th className="num">Amount USDC</th><th>Outcome</th><th>Block / transaction</th><th><span className="sr-only">Open details</span></th></tr></thead><tbody>{allRows.map(row=><tr key={row.id}><td>{row.action}<span className="cell-secondary">{row.source==='recorded'?'Recorded evidence':row.kind==='simulation'?'Local simulation · no transaction':'This browser'} · {row.timestamp.slice(0,10)}</span></td><td className="num">{row.amount?money(BigInt(row.amount)):'—'}</td><td><Badge state={row.status}>{row.status==='reverted'?'HELD · REVERTED':row.status.toUpperCase()}</Badge></td><td>{row.hash?<a className="mono" href={`${explorer}/tx/${row.hash}`}>{short(row.hash)} ↗</a>:<span className="caption">No transaction hash</span>}<span className="cell-secondary">{row.block?`Block ${blockNumber(row.block)}`:'Not mined / unresolved'}</span></td><td><button data-ledger-detail onClick={()=>setDetail(row)} aria-label={`Details for ${row.action} ${row.block?blockNumber(row.block):row.status}`}>Details</button>{row.hash&&row.source==='local'&&['pending','unknown'].includes(row.status)&&<button onClick={()=>void reconcile(row)}>Check receipt</button>}{!row.hash&&row.source==='local'&&['unknown','awaiting'].includes(row.status)&&<button onClick={()=>{record({...row,status:'cancelled',message:'Operator acknowledged wallet activity; no hash was returned to this browser.'});}}>Acknowledge after checking wallet</button>}</td></tr>)}</tbody></table>{!allRows.length&&<p className="empty">No matching decisions.</p>}</div>
      </Panel>
      <footer className="desk-footer"><p>Signa Covenant · authenticated coverage as a condition of capital.</p><p>Fictional facility. Mock assertions. Testnet USDC. No bank has agreed to sign anything.</p><a href="mailto:m@oakgroup.co">Talk to us</a><span> · </span><a href="/architecture.html">Architecture</a><span> · </span><a href="https://github.com/estmcmxci/signa-arc">Source ↗</a></footer>
    </main>
    <Modal open={!!confirmation} onOpenChange={open=>{if(!open)setConfirmation(null);}} title="Review transaction"><p>{confirmation} {confirmation==='draw'||confirmation==='repay'?`${money(parsed,6)} USDC`:''}</p><p className="caption">Arc Testnet · chain 5042002</p>{connection.address&&<><p>Signing account</p><Copy value={connection.address} full/></>}{m&&<><p>Covenant vault</p><Copy value={m.contracts.covenantVault.address} full/></>}{confirmation==='repay'&&<p>If allowance is insufficient, your wallet first approves this exact amount. Approval and repayment are separate transactions. Repayment is re-simulated after approval.</p>}<p>The requested action is freshly simulated before each wallet request. State can change before the transaction is mined.</p><button className="primary" onClick={()=>void submit()}>Continue to wallet</button></Modal>
    <Modal open={!!detail} onOpenChange={open=>{if(!open)setDetail(null);}} title="Decision detail">{detail&&<ReceiptDetail row={detail}/>}</Modal>
    <Modal open={!!credential} onOpenChange={open=>{if(!open)setCredential(null);}} title="Assertion admissibility">{credential&&<CredentialDetail hedge={credential} snapshot={snapshot}/>}</Modal>
    <Modal open={commandOpen} onOpenChange={setCommandOpen} title="Go to…"><div className="command-list">{[['Evaluate a draw','actions'],['Inspect assertions','credentials'],['Review governed exceptions','waiver'],['Read the ledger','ledger']].map(([label,id])=><button key={id} onClick={()=>{setCommandOpen(false);setTimeout(()=>{document.getElementById(id!)?.scrollIntoView({behavior:'instant'});if(id==='actions')amountRef.current?.focus();},0);}}>{label}</button>)}</div><p className="caption">D focuses the amount · S focuses sync · J/K moves through ledger details. Shortcuts never submit a transaction.</p></Modal>
  </div>;
}

function Metric({label,help,value,unit,note,children}:{label:string;help:string;value:string;unit?:string;note:string;children?:ReactNode}){return <article className="metric"><Help label={label}>{help}</Help><div className="metric-number" title={value}>{children??value}{unit&&<span className="unit"> {unit}</span>}</div><p className="caption">{note}</p></article>;}
function Fact({label,value,help}:{label:string;value:string;help:string}){return <div><dt><Help label={label}>{help}</Help></dt><dd>{value}</dd></div>;}
function CoverageBar({snapshot}:{snapshot:Snapshot|undefined}){const c=snapshot?.coverage;if(!c)return <p className="empty">Awaiting engine coverage.</p>;const gross=grossBps(c.grossEligible,c.outstandingValue);const max=Math.max(150,gross===null?100:Number(gross/100n));const counted=c.coverageBps/100/max*100;const surplus=Math.max(0,Number(gross??0n)/100-100)/max*100;return <div className="coverage-meter"><div className="bar" role="meter" aria-label="Counted coverage" aria-valuemin={0} aria-valuemax={100} aria-valuenow={c.coverageBps/100} aria-valuetext={`${percent(c.coverageBps)} counted, ${percent(gross)} gross, ${percent(c.requiredCoverageBps)} required`}><div className="counted" style={{width:`${counted}%`}}/><div className="surplus" style={{left:`${100/max*100}%`,width:`${surplus}%`}}/><span className="threshold" style={{left:`${c.requiredCoverageBps/100/max*100}%`}}/></div><div className="bar-labels"><span>0%</span><span>{percent(c.requiredCoverageBps)} minimum / 100% cap</span><span>{max}%</span></div>{surplus>0&&<p className="caption hatch-key">Hatched: surplus notional, not counted.</p>}</div>;}
function Sparkline({points,threshold}:{points:{block:bigint;bps:number}[];threshold:number}){if(points.length<2)return <p className="caption">Coverage observations will appear as this session receives blocks.</p>;const min=Math.min(threshold,...points.map(p=>p.bps))-100,max=Math.max(threshold,...points.map(p=>p.bps))+100;const y=(v:number)=>65-(v-min)/(max-min)*55;const path=points.map((p,i)=>`${i?'L':'M'}${i/(points.length-1)*320},${y(p.bps)}`).join(' ');return <figure className="sparkline"><svg viewBox="0 0 320 72" role="img" aria-label={`Coverage observed across ${points.length} snapshots in this browser session; latest ${percent(points.at(-1)!.bps)}.`}><line x1="0" x2="320" y1={y(threshold)} y2={y(threshold)} stroke="var(--muted)" strokeDasharray="4 4"/><path d={path} fill="none" stroke="var(--text)" strokeWidth="1.5"/></svg><figcaption>Observed this session · dashed line is the policy minimum</figcaption></figure>;}
function ReceiptDetail({row}:{row:LedgerRow}){return <div className="receipt-detail"><Badge state={row.status}/><h3>{row.action}</h3>{row.amount&&<p className="receipt-amount">{money(BigInt(row.amount),6)} <span>USDC</span></p>}<p>{row.source==='recorded'?'Historical evidence; not a current-state claim.':row.kind==='simulation'?'A local simulation. No transaction was submitted.':'A transaction initiated in this browser.'}</p>{row.message&&<p>{row.message}</p>}{row.status==='reverted'&&<p>Included in a block; gas was spent and this transaction’s changes were rolled back.</p>}<dl className="facts"><Fact label="Recorded at" value={row.timestamp} help="Evidence recording or browser submission time; not necessarily block time."/><Fact label="Block time" value={row.blockTimestamp??'Not recorded'} help="Timestamp of the inclusion block when available."/><Fact label="Block" value={row.block?blockNumber(row.block):'Not mined / unresolved'} help="A simulation block does not imply inclusion."/><Fact label="Nonce" value={row.nonce?.toString()??'Not recorded'} help="Transaction sequence for this sender."/><Fact label="Fee USDC" value={row.feeNative?formatUnits(BigInt(row.feeNative),18):'Not recorded'} help="Native USDC gas uses eighteen decimals; it is the same asset, not an additional balance."/></dl>{row.before&&<div className="before-after"><h3>Before → after</h3><p>Vault balance {row.before.balance?money(BigInt(row.before.balance),6):'—'} → {row.after?.balance?money(BigInt(row.after.balance),6):'—'} USDC</p><p>Principal {row.before.principal?money(BigInt(row.before.principal),6):'—'} → {row.after?.principal?money(BigInt(row.after.principal),6):'—'} USDC</p><p className="caption">Before is the recorded pre-action snapshot; after is the receipt-block state when available.</p></div>}{row.hash&&<><h3>Transaction hash</h3><Copy value={row.hash} label="transaction hash" full/><p><a href={`${explorer}/tx/${row.hash}`}>Inspect receipt on Arcscan ↗</a></p></>}{row.actor&&<><h3>Actor</h3><Copy value={row.actor} label="actor" full/></>}{row.originalHash&&<><h3>Replaced hash</h3><Copy value={row.originalHash} full/></>}{row.code&&<><h3>Reason</h3><Copy value={row.code} label="reason code" full/></>}{row.amount&&<><h3>Raw amount · six-decimal base units</h3><Copy value={row.amount} full/></>}{row.detail&&<details><summary>Wallet and RPC detail</summary><pre>{row.detail}</pre></details>}{row.input&&<details><summary>Transaction input</summary><Copy value={row.input} label="calldata" full/></details>}{row.events&&<details><summary>Decoded events ({row.events.length})</summary><pre>{json(row.events)}</pre></details>}<p className="caption">The covenant evaluates again on synchronization or the next draw. A receipt describes that transaction, not a permanent permission.</p></div>;}
function CredentialDetail({hedge:h,snapshot}:{hedge:Hedge;snapshot:Snapshot|undefined}){const code=h.eligibilityReason===null?'UNAVAILABLE':HEDGE_REASONS[h.eligibilityReason]??'UNKNOWN';const reason=REASONS[code];return <div><span className="mock-tag">Mock issuer / provider data</span><h3>{reason?.title??'Eligibility unavailable'}</h3><p>{reason?.explanation}</p><dl className="facts"><Fact label="Remaining notional" value={`${money(h.credential.remainingNotional,6)} USDC`} help="Provider assertion before haircut."/><Fact label="Counted by engine before aggregate cap" value={`${money(h.adjustedNotional,6)} USDC`} help="Engine-returned adjusted notional for this hedge."/><Fact label="Hedge maturity" value={utc(h.credential.maturity)} help="Signed hedge maturity timestamp."/><Fact label="Exposure maturity" value={utc(snapshot?.exposure?.credential.exposureMaturity)} help="Signed obligation maturity timestamp."/><Fact label="Policy tolerance" value={snapshot?.policy?duration(snapshot.policy.maturityTolerance):'—'} help="Frozen maturity tolerance; changing it requires a different facility."/><Fact label="Observed" value={utc(h.credential.observedAt)} help="Issuer observation timestamp."/><Fact label="Valid until" value={utc(h.credential.validUntil)} help="Signed validity window; maximum age can expire sooner."/><Fact label="Sequence" value={h.credential.sequence.toString()} help="Higher sequences supersede earlier assertions for this trade."/></dl><p>{reason?.remedy}</p><p className="caption">Who can act: {reason?.actor??'Issuer'}. This is the engine’s returned eligibility reason, not a reconstructed full trace.</p><Copy value={code} label="eligibility code" full/><h3>Signed digest</h3><Copy value={h.digest} label="credential digest" full/><h3>Source commitment</h3><Copy value={h.credential.sourceCommitment} full/></div>;}
