// Generated by scripts/generate-abis.ts from the Foundry build of contracts/src. Do not edit.
// Regenerate with `forge build && pnpm generate:abis`. scripts/test/generate-abis.test.ts checks for drift.

/** FacilityRegistry, from contracts/src/FacilityRegistry.sol. */
export const facilityRegistryAbi = [
  {
    "type": "function",
    "name": "MAX_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_HEDGES",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createFacility",
    "inputs": [
      {
        "name": "policy",
        "type": "tuple",
        "internalType": "struct FacilityRegistry.FacilityPolicy",
        "components": [
          {
            "name": "facilityId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "settlementCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "exposureCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "minCoverageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "credentialMaxAge",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maturityTolerance",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "defaultHaircutBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "reserveAmount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "curePeriod",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxWaiverDuration",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxActiveHedges",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "settlementAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "admin",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "operator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "frozen",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "exposureIssuerEpoch",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "epoch",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "facilityExists",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "freezeFacility",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getFacility",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct FacilityRegistry.FacilityPolicy",
        "components": [
          {
            "name": "facilityId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "settlementCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "exposureCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "minCoverageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "credentialMaxAge",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maturityTolerance",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "defaultHaircutBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "reserveAmount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "curePeriod",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxWaiverDuration",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxActiveHedges",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "settlementAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "admin",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "operator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "frozen",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hedgeIssuerEpoch",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "epoch",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isExposureIssuer",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isHedgeIssuer",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setExposureIssuer",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "authorized",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setHedgeIssuer",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "authorized",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "ExposureIssuerAuthorizationChanged",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "authorized",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "authorizationEpoch",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FacilityCreated",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "admin",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FacilityFrozen",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HedgeIssuerAuthorizationChanged",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "authorized",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "authorizationEpoch",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "FacilityAlreadyExists",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "FacilityAlreadyFrozen",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "FacilityNotFound",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidPolicy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "IssuerRoleConflict",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "MissingIssuerRole",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotFacilityAdmin",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const;

/** CredentialRegistry, from contracts/src/CredentialRegistry.sol. */
export const credentialRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "facilityRegistry_",
        "type": "address",
        "internalType": "contract FacilityRegistry"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "DOMAIN_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EIP712_NAME",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EIP712_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EXPOSURE_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "HEDGE_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "currentExposure",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct CredentialRegistry.StoredExposure",
        "components": [
          {
            "name": "credential",
            "type": "tuple",
            "internalType": "struct CredentialRegistry.ExposureCredential",
            "components": [
              {
                "name": "facilityId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "exposureCurrency",
                "type": "bytes3",
                "internalType": "bytes3"
              },
              {
                "name": "settlementCurrency",
                "type": "bytes3",
                "internalType": "bytes3"
              },
              {
                "name": "outstandingValue",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "exposureMaturity",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "observedAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "validUntil",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sequence",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sourceCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "issuer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "digest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "acceptedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "issuerEpoch",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "currentHedge",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "tradeIdCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct CredentialRegistry.StoredHedge",
        "components": [
          {
            "name": "credential",
            "type": "tuple",
            "internalType": "struct CredentialRegistry.HedgeCredential",
            "components": [
              {
                "name": "facilityId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "tradeIdCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "baseCurrency",
                "type": "bytes3",
                "internalType": "bytes3"
              },
              {
                "name": "quoteCurrency",
                "type": "bytes3",
                "internalType": "bytes3"
              },
              {
                "name": "remainingNotional",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "maturity",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "status",
                "type": "uint8",
                "internalType": "enum CredentialRegistry.HedgeStatus"
              },
              {
                "name": "observedAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "validUntil",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sequence",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "sourceCommitment",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "issuer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "digest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "acceptedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "issuerEpoch",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "domainSeparator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "facilityRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract FacilityRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashExposureCredential",
    "inputs": [
      {
        "name": "credential",
        "type": "tuple",
        "internalType": "struct CredentialRegistry.ExposureCredential",
        "components": [
          {
            "name": "facilityId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "exposureCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "settlementCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "outstandingValue",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "exposureMaturity",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "observedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sequence",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sourceCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashHedgeCredential",
    "inputs": [
      {
        "name": "credential",
        "type": "tuple",
        "internalType": "struct CredentialRegistry.HedgeCredential",
        "components": [
          {
            "name": "facilityId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tradeIdCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "baseCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "quoteCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "remainingNotional",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "maturity",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum CredentialRegistry.HedgeStatus"
          },
          {
            "name": "observedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sequence",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sourceCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hedgeTradeIds",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "revokeExposure",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeHedge",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "tradeIdCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokedDigests",
    "inputs": [
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "revoked",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitExposure",
    "inputs": [
      {
        "name": "credential",
        "type": "tuple",
        "internalType": "struct CredentialRegistry.ExposureCredential",
        "components": [
          {
            "name": "facilityId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "exposureCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "settlementCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "outstandingValue",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "exposureMaturity",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "observedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sequence",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sourceCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitHedge",
    "inputs": [
      {
        "name": "credential",
        "type": "tuple",
        "internalType": "struct CredentialRegistry.HedgeCredential",
        "components": [
          {
            "name": "facilityId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tradeIdCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "baseCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "quoteCurrency",
            "type": "bytes3",
            "internalType": "bytes3"
          },
          {
            "name": "remainingNotional",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "maturity",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum CredentialRegistry.HedgeStatus"
          },
          {
            "name": "observedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sequence",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sourceCommitment",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "CredentialRevoked",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "revokedBy",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExposureCredentialAccepted",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "sequence",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "outstandingValue",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "acceptedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HedgeCredentialAccepted",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "tradeIdCommitment",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "sequence",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "status",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum CredentialRegistry.HedgeStatus"
      },
      {
        "name": "remainingNotional",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "acceptedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyRevoked",
    "inputs": [
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "FacilityNotFrozen",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidCredential",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotCredentialController",
    "inputs": [
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "StaleSequence",
    "inputs": [
      {
        "name": "supplied",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "current",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "TooManyHedges",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnauthorizedIssuer",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "issuer",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const;

/** CoverageEngine, from contracts/src/CoverageEngine.sol. */
export const coverageEngineAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "facilityRegistry_",
        "type": "address",
        "internalType": "contract FacilityRegistry"
      },
      {
        "name": "credentialRegistry_",
        "type": "address",
        "internalType": "contract CredentialRegistry"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assess",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "allowed",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "reason",
        "type": "uint8",
        "internalType": "enum CoverageEngine.ResultReason"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "credentialRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract CredentialRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "evaluate",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "result",
        "type": "tuple",
        "internalType": "struct CoverageEngine.CoverageResult",
        "components": [
          {
            "name": "assessed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "compliant",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "outstandingValue",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "grossEligible",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "countedEligible",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "coverageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "requiredCoverageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "eligibleHedgeCount",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "totalHedgeCount",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "exposureReason",
            "type": "uint8",
            "internalType": "enum CoverageEngine.ExposureReason"
          },
          {
            "name": "resultReason",
            "type": "uint8",
            "internalType": "enum CoverageEngine.ResultReason"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "exposureEligibility",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum CoverageEngine.ExposureReason"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "facilityRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract FacilityRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hedgeEligibility",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "tradeIdCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "reason",
        "type": "uint8",
        "internalType": "enum CoverageEngine.HedgeReason"
      },
      {
        "name": "adjustedNotional",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  }
] as const;

/** CovenantVault, from contracts/src/CovenantVault.sol. */
export const covenantVaultAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "facilityId_",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "facilityRegistry_",
        "type": "address",
        "internalType": "contract FacilityRegistry"
      },
      {
        "name": "coverageEngine_",
        "type": "address",
        "internalType": "contract CoverageEngine"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "activeWaiver",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "availableToDraw",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "covenantState",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum CovenantVault.CovenantState"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "coverageEngine",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract CoverageEngine"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createWaiver",
    "inputs": [
      {
        "name": "duration",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "reasonCommitment",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cureDeadline",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deposit",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "draw",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "facilityId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "facilityRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract FacilityRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "principal",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "repay",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "restoreCompliance",
    "inputs": [],
    "outputs": [
      {
        "name": "result",
        "type": "tuple",
        "internalType": "struct CoverageEngine.CoverageResult",
        "components": [
          {
            "name": "assessed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "compliant",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "outstandingValue",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "grossEligible",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "countedEligible",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "coverageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "requiredCoverageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "eligibleHedgeCount",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "totalHedgeCount",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "exposureReason",
            "type": "uint8",
            "internalType": "enum CoverageEngine.ExposureReason"
          },
          {
            "name": "resultReason",
            "type": "uint8",
            "internalType": "enum CoverageEngine.ResultReason"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeWaiver",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settlementAsset",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20Settlement"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "stateBeforeWaiver",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum CovenantVault.CovenantState"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "syncCovenant",
    "inputs": [],
    "outputs": [
      {
        "name": "result",
        "type": "tuple",
        "internalType": "struct CoverageEngine.CoverageResult",
        "components": [
          {
            "name": "assessed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "compliant",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "outstandingValue",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "grossEligible",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "countedEligible",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "coverageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "requiredCoverageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "eligibleHedgeCount",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "totalHedgeCount",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "exposureReason",
            "type": "uint8",
            "internalType": "enum CoverageEngine.ExposureReason"
          },
          {
            "name": "resultReason",
            "type": "uint8",
            "internalType": "enum CoverageEngine.ResultReason"
          }
        ]
      },
      {
        "name": "state",
        "type": "uint8",
        "internalType": "enum CovenantVault.CovenantState"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "waiverEndsAt",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "waiverReasonCommitment",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "CovenantSynchronized",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousState",
        "type": "uint8",
        "indexed": true,
        "internalType": "enum CovenantVault.CovenantState"
      },
      {
        "name": "newState",
        "type": "uint8",
        "indexed": true,
        "internalType": "enum CovenantVault.CovenantState"
      },
      {
        "name": "coverageBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "requiredCoverageBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "outstandingValue",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "grossEligible",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "countedEligible",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "reason",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum CoverageEngine.ResultReason"
      },
      {
        "name": "cureDeadline",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Deposited",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "from",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Drawn",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "principal",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Repaid",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "principal",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WaiverCreated",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reasonCommitment",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "startsAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "endsAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WaiverRevoked",
    "inputs": [
      {
        "name": "facilityId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reasonCommitment",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "DrawNotAllowed",
    "inputs": [
      {
        "name": "state",
        "type": "uint8",
        "internalType": "enum CovenantVault.CovenantState"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidWaiver",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoActiveWaiver",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAdmin",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotOperator",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "Reentrancy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveViolation",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "requested",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "reserve",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TokenTransferFailed",
    "inputs": []
  }
] as const;
