import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

/**
 * Writes packages/client/src/abis.ts from the Foundry build. Runtime code never reads
 * contracts/out (ERD §4). The output is deterministic: the same build always produces the same
 * file, and scripts/test/generate-abis.test.ts fails when the checked-in module drifts from it.
 *
 *   forge build && pnpm generate:abis
 */

export const ABI_CONTRACTS = [
  ["facilityRegistryAbi", "FacilityRegistry"],
  ["credentialRegistryAbi", "CredentialRegistry"],
  ["coverageEngineAbi", "CoverageEngine"],
  ["covenantVaultAbi", "CovenantVault"],
] as const;

const ROOT = new URL("../", import.meta.url);
export const ABI_MODULE = new URL("packages/client/src/abis.ts", ROOT);

export function renderAbiModule(): string {
  const sections = ABI_CONTRACTS.map(([exportName, contract]) => {
    const artifactUrl = new URL(`contracts/out/${contract}.sol/${contract}.json`, ROOT);
    let artifact: { abi?: unknown };
    try {
      artifact = JSON.parse(readFileSync(artifactUrl, "utf8")) as { abi?: unknown };
    } catch (error) {
      throw new Error(`cannot read the Foundry artifact for ${contract}: run forge build first (${String(error)})`);
    }
    if (!Array.isArray(artifact.abi)) throw new Error(`the ${contract} artifact has no abi array`);
    return `/** ${contract}, from contracts/src/${contract}.sol. */\nexport const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  });
  return [
    "// Generated by scripts/generate-abis.ts from the Foundry build of contracts/src. Do not edit.",
    "// Regenerate with `forge build && pnpm generate:abis`. scripts/test/generate-abis.test.ts checks for drift.",
    "",
    ...sections,
  ].join("\n");
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  writeFileSync(ABI_MODULE, renderAbiModule());
  console.log(`wrote ${ABI_MODULE.pathname}`);
}
