import {
  createPrivateKey,
  createPublicKey,
  generateKeyPairSync,
  sign,
  verify,
  type KeyObject,
} from "node:crypto";

/**
 * Privy authorization signatures, implemented without `@privy-io/node`.
 *
 * Reproduces `formatRequestForAuthorizationSignature` and `generateAuthorizationSignature` from
 * `@privy-io/node@0.34.0` (`src/lib/authorization.ts`): the RFC 8785 canonical JSON of
 * `{ version, method, url, body, headers }`, UTF-8 encoded, signed with ECDSA P-256 over SHA-256,
 * DER-encoded, base64. `test/authorization.test.ts` pins byte equality with vectors generated by
 * that SDK, so no Privy dependency is needed to trust this file. Intent authorizations add
 * `intent_id` and `timestamp`: see `intentAuthorizationInput`.
 */

export type HttpMethod = "POST" | "PUT" | "PATCH" | "DELETE";

export type PrivyHeaders = {
  "privy-app-id": string;
  "privy-idempotency-key"?: string;
  "privy-request-expiry"?: string;
};

export type AuthorizationPayloadInput = {
  version: 1;
  method: HttpMethod;
  url: string;
  body: unknown;
  headers: PrivyHeaders;
  /** Intent authorizations only: binds the signature to one intent. */
  intent_id?: string;
  /** Intent authorizations only: equals the authorize request's `timestamp`. */
  timestamp?: number;
};

/** The request an intent records and will execute once authorized: `request_details`. */
export type IntentRequestDetails = { method: HttpMethod; url: string; body: unknown };

/** The parts of an intent its authorization signature covers. */
export type AuthorizableIntent = { intent_id: string; request_details: IntentRequestDetails };

/** Privy rejects an intent authorization whose `timestamp` is more than this far from its clock. */
export const INTENT_SIGNATURE_WINDOW_MS = 300_000;

export type AuthorizationKeyPair = { publicKey: string; privateKey: string };

const PRIVATE_KEY_PREFIXES = ["wallet-auth:", "wallet-api:"] as const;

/**
 * RFC 8785 JSON Canonicalization Scheme, matching the `canonicalize` package Privy's SDK uses:
 * keys sorted by UTF-16 code unit, no whitespace, ECMAScript number serialisation.
 */
export function canonicalize(value: unknown): string {
  if (typeof value === "number" && !Number.isFinite(value)) {
    throw new TypeError(`canonical JSON cannot encode ${value}`);
  }
  if (value === null || typeof value !== "object") {
    const encoded: string | undefined = JSON.stringify(value);
    if (encoded === undefined) throw new TypeError(`canonical JSON cannot encode ${typeof value}`);
    return encoded;
  }
  const withToJson = value as { toJSON?: () => unknown };
  if (typeof withToJson.toJSON === "function") return canonicalize(withToJson.toJSON());
  if (Array.isArray(value)) {
    const items = value.map((item: unknown) =>
      canonicalize(item === undefined || typeof item === "symbol" ? null : item),
    );
    return `[${items.join(",")}]`;
  }
  const record = value as Record<string, unknown>;
  const members = Object.keys(record)
    .sort()
    .filter((key) => record[key] !== undefined && typeof record[key] !== "symbol")
    .map((key) => `${JSON.stringify(key)}:${canonicalize(record[key])}`);
  return `{${members.join(",")}}`;
}

/** The bytes an authorization signature covers. An empty body is signed as `""`, as the SDK does. */
export function formatAuthorizationPayload(input: AuthorizationPayloadInput): Uint8Array<ArrayBuffer> {
  const emptyBody =
    typeof input.body === "object" && input.body !== null && Object.keys(input.body).length === 0;
  return new TextEncoder().encode(canonicalize({ ...input, body: emptyBody ? "" : input.body }));
}

/**
 * The payload an approver signs for `POST /v1/intents/{id}/authorize`, as the live API verifies
 * it (proven 2026-09-10). It is the standard authorization payload over the intent's underlying
 * request, plus two top-level fields Privy's documentation never mentions: `intent_id` and
 * `timestamp`. They are required together; either one alone is rejected exactly like a wrong
 * signature. `@privy-io/js-sdk-core` declares both on `GenerateAuthorizationSignatureInput`, with
 * `intent_id` there to prevent cross-intent replay.
 *
 * - `body` must be Privy's normalized copy from `GET /v1/intents/{id}`, never the proposed body.
 * - `timestamp` must equal the `timestamp` sent beside the signature, within
 *   `INTENT_SIGNATURE_WINDOW_MS` of Privy's clock.
 * - Privy returns "No valid authorization key found for signature" for an empty signature too,
 *   so that error says nothing about which part is wrong.
 */
export function intentAuthorizationInput(
  intent: AuthorizableIntent,
  appId: string,
  timestamp: number,
): AuthorizationPayloadInput {
  const request = intent.request_details;
  return {
    version: 1,
    method: request.method,
    url: request.url,
    body: request.body,
    headers: { "privy-app-id": appId },
    intent_id: intent.intent_id,
    timestamp,
  };
}

/** Imports a base64 PKCS8 P-256 private key, with or without Privy's `wallet-auth:` prefix. */
export function importAuthorizationPrivateKey(encoded: string): KeyObject {
  let der = encoded.trim();
  for (const prefix of PRIVATE_KEY_PREFIXES) {
    if (der.startsWith(prefix)) der = der.slice(prefix.length);
  }
  const key = createPrivateKey({ key: Buffer.from(der, "base64"), format: "der", type: "pkcs8" });
  assertP256(key);
  return key;
}

/**
 * Imports a P-256 public key given as bare base64 SPKI or as PEM. Privy uses both for one key:
 * `GET /v1/key_quorums/{id}` lists `authorization_keys[].public_key` as bare SPKI, while an
 * intent's `authorization_details[].members[].public_key` carries the same key in PEM armour.
 */
export function importAuthorizationPublicKey(encoded: string): KeyObject {
  const trimmed = encoded.trim();
  const key = trimmed.startsWith("-----BEGIN")
    ? createPublicKey({ key: trimmed, format: "pem" })
    : createPublicKey({ key: Buffer.from(trimmed, "base64"), format: "der", type: "spki" });
  assertP256(key);
  return key;
}

/** One spelling per key, bare base64 SPKI, so keys from different Privy responses compare equal. */
export function normalizePublicKey(encoded: string): string {
  return importAuthorizationPublicKey(encoded).export({ format: "der", type: "spki" }).toString("base64");
}

/** A fresh key pair in Privy's formats: base64 SPKI public key, base64 PKCS8 private key. */
export function generateAuthorizationKeyPair(): AuthorizationKeyPair {
  const { publicKey, privateKey } = generateKeyPairSync("ec", { namedCurve: "prime256v1" });
  return {
    publicKey: publicKey.export({ format: "der", type: "spki" }).toString("base64"),
    privateKey: privateKey.export({ format: "der", type: "pkcs8" }).toString("base64"),
  };
}

export function publicKeyOf(privateKey: string): string {
  return createPublicKey(importAuthorizationPrivateKey(privateKey))
    .export({ format: "der", type: "spki" })
    .toString("base64");
}

/** ECDSA P-256 over SHA-256, DER-encoded, base64: the format Privy's SDK sends. */
export function signAuthorizationPayload(privateKey: string, payload: Uint8Array): string {
  return sign("sha256", payload, importAuthorizationPrivateKey(privateKey)).toString("base64");
}

export function verifyAuthorizationSignature(
  publicKey: string,
  payload: Uint8Array,
  signature: string,
): boolean {
  return verify(
    "sha256",
    payload,
    importAuthorizationPublicKey(publicKey),
    Buffer.from(signature, "base64"),
  );
}

/**
 * WebCrypto's ECDSA output is IEEE P1363 (`r || s`, 64 bytes); Privy expects DER. The approver UI
 * signs in the browser and sends P1363, and the server converts here so the conversion is tested.
 */
export function p1363ToDer(signature: Uint8Array): Uint8Array {
  if (signature.length !== 64) {
    throw new TypeError(`expected a 64-byte P-256 signature, got ${signature.length} bytes`);
  }
  const r = derInteger(signature.subarray(0, 32));
  const s = derInteger(signature.subarray(32));
  return Uint8Array.from([0x30, r.length + s.length, ...r, ...s]);
}

function derInteger(bytes: Uint8Array): number[] {
  let start = 0;
  while (start < bytes.length - 1 && bytes[start] === 0) start++;
  const value = Array.from(bytes.subarray(start));
  if (((value[0] ?? 0) & 0x80) !== 0) value.unshift(0);
  return [0x02, value.length, ...value];
}

function assertP256(key: KeyObject): void {
  if (key.asymmetricKeyType !== "ec" || key.asymmetricKeyDetails?.namedCurve !== "prime256v1") {
    throw new TypeError("Privy authorization keys must be P-256");
  }
}
